language: ruby
rvm:
  - 1.9.3
  - 2.1.2
  - 2.2.4
  - 2.3.0
  - rbx
  - jruby-1.7.26
  - jruby-9.1.5.0
  - jruby-9.1.6.0
  - jruby-head
before_install:
  - gem update --system
  - gem --version  
script:
  - bundle exec rspec spec/temp_file_spec.rb
